version: "3.9"
services:
  orchestrator-test:
    build: ./apps/orchestrator
    environment:
      - ZAI_API_KEY=4f551480d98847fb8c78c67ec162ea1c.hHH8OozRiOCeWUAU
      - NODE_ENV=development
      - MODEL=claude-sonnet-4-5-20250929
      - LOG_LEVEL=debug
      - MAX_ITERATIONS=2
      - MAX_RETRIES=1
      - DEFAULT_TIMEOUT=60000
      - MAX_CONCURRENT_OPS=3
      - ANTHROPIC_BASE_URL=https://api.z.ai/api/anthropic
      - API_TIMEOUT_MS=3000000
    volumes:
      - ./project:/project
      - test_claude_home:/root/.claude
    working_dir: /project
    # Don't restart for test
    restart: "no"
    command: ["node", "dist/index.js"]

volumes:
  test_claude_home: